#!/usr/bin/perl -w
#
# hydra² - Claws Mail CVS Debian Packages Autobuilder script (again!)
#
# Copyright (c) 2008-2011 Ricardo Mones <ricardo@mones.org>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy  of this  software and  associated  documentation  files  (the
# "Software"), to deal in the  Software without  restriction, including
# without  limitation  the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or  sell copies  of the  Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The  above  copyright  notice and  this  permission  notice  shall be
# included in  all  copies  or substantial  portions  of the  Software.
#
# THE  SOFTWARE IS  PROVIDED "AS IS",  WITHOUT  WARRANTY OF  ANY  KIND,
# EXPRESS  OR  IMPLIED,  INCLUDING BUT  NOT LIMITED  TO THE  WARRANTIES
# OF  MERCHANTABILITY,   FITNESS   FOR   A   PARTICULAR   PURPOSE   AND
# NONINFRINGEMENT. IN  NO EVENT SHALL THE AUTHORS OR  COPYRIGHT HOLDERS
# BE  LIABLE FOR ANY CLAIM,  DAMAGES OR OTHER  LIABILITY, WHETHER IN AN
# ACTION  OF  CONTRACT, TORT OR  OTHERWISE, ARISING  FROM, OUT OF OR IN
# CONNECTION  WITH THE  SOFTWARE OR  THE USE OR  OTHER  DEALINGS IN THE
# SOFTWARE.
#
use strict;
use encoding 'utf8';

my $CVS = ':pserver:anonymous@claws-mail.org:/';
my $MKD = 'Makefile.dist';
my $MKA = 'Makefile.arch';
my $VER = undef;
my $OLD = undef;

sub refresh_module {
  my $mod = shift; # claws or plugins
  if (-d $mod) {
    chdir($mod);
    qx,cvs -z3 update,;
    chdir("..");
  } else {
    qx,cvs -z3 -d$CVS checkout -r gtk2 $mod,;
  }
}

sub get_version {
  my $acfile = shift;
  my @ver = ("0", "0", "0", "0");
  if (-f $acfile) {
    open(AC, "< $acfile") or die "opening $acfile: $!\n";
    my $i = 0;
    while (<AC>) {
      chomp;
      if (/MAJOR_VERSION=(\d+)/) { $ver[0] = $1; ++$i; }
      if (/MINOR_VERSION=(\d+)/) { $ver[1] = $1; ++$i; }
      if (/MICRO_VERSION=(\d+)/) { $ver[2] = $1; ++$i; }
      if (/EXTRA_VERSION=(\d+)/) { $ver[3] = $1; ++$i; }
      last unless ($i lt 4);
    }
    close(AC) or die "closing configure.ac: $!\n";
  }
  return join('.', @ver);
}

sub is_greater_version {
  my ($va, $vb) = @_;
  my @vaa = split(/\./, $va);
  my @vba = split(/\./, $vb);
  my $i = 0;
  while (defined($vaa[$i]) and defined($vba[$i])) {
    last if ($vaa[$i] != $vba[$i]);
    ++$i;
  }
  my $res = ($vaa[$i] > $vba[$i])? 1: 0;
  return $res;
}

sub check_make_error {
  my $log = shift;
  open (LOG, "<$log") or die "opening $log: $!\n";
  my $last = <LOG>;
  while (<LOG>) { $last = $_ }
  close(LOG) or die "closing $log: $!\n" ;
  $_ = $last;
  die "Finished with error. Check $log for details.\n"
    if (/^make.*Error/);
}

&refresh_module ("claws");
&refresh_module ("plugins");
$VER = &get_version ("claws/configure.ac");
$OLD = &get_version ("claws-dev/configure.ac");
if (&is_greater_version ($VER, $OLD)) {
  my $logname = "logs/hydra.$VER.log";
  print "Building new version $VER (previus was $OLD)\n";
  qx,make -f $MKD VERSION=$VER > $logname 2>&1,;
  &check_make_error($logname);
  foreach my $ARCH ("amd64", "i386") {
    print "Archiving previous $OLD packages for $ARCH\n";
    qx,make -f $MKA VERSION=$OLD ARCH=$ARCH backup >> $logname 2>&1,;
    &check_make_error($logname);
    print "Building new $VER packages for $ARCH\n";
    qx,make -f $MKA VERSION=$VER ARCH=$ARCH >> $logname 2>&1,;
    &check_make_error($logname);
  }
}

