#!/usr/bin/perl -w
#
# hydra² - Claws Mail CVS Debian Packages Autobuilder script (again!)
#
# See LICENSE file for licensing details.
#
use strict;
use encoding 'utf8';
use Mail::Sendmail;

my $CVS = ':pserver:anonymous@claws-mail.org:/';
my ($VER, $OLD) = (undef, undef);
my ($RVER, $ROLD) = (undef, undef);
my $WHO = undef;

my $RUN = $ARGV[0];
die "Run dir required\n" unless (defined($RUN) and -d $RUN);
my $HYD = $ARGV[1];
$HYD = $RUN unless defined($HYD);
die "Makefiles dir required\n" unless (-d $HYD);
my $MKD = "$HYD/Makefile.dist";
my $MKA = "$HYD/Makefile.arch";
my $MKS = "$HYD/Makefile.stat";
foreach my $mkfl ($MKD, $MKA, $MKS) {
  die "$mkfl not found\n" unless (-f $mkfl);
}

sub refresh_module {
  my $mod = shift; # claws
  if (-d $mod) {
    chdir($mod);
    qx,cvs -z3 update > /dev/null 2>&1,;
    chdir("..");
  } else {
    qx,cvs -z3 -d$CVS checkout -r gtk2 $mod > /dev/null 2>&1,;
  }
}

sub get_version {
  my $acfile = shift;
  my @ver = ("0", "0", "0", "0");
  if (-f $acfile) {
    open(AC, "< $acfile") or die "opening $acfile: $!\n";
    my $i = 0;
    while (<AC>) {
      chomp;
      if (/MAJOR_VERSION=(\d+)/) { $ver[0] = $1; ++$i; }
      if (/MINOR_VERSION=(\d+)/) { $ver[1] = $1; ++$i; }
      if (/MICRO_VERSION=(\d+)/) { $ver[2] = $1; ++$i; }
      if (/EXTRA_VERSION=(\d+)/) { $ver[3] = $1; ++$i; }
      last unless ($i lt 4);
    }
    close(AC) or die "closing configure.ac: $!\n";
  }
  return join('.', @ver);
}

sub get_real_version {
  $_ = shift;
  if (/(\d+)\.(\d+)\.(\d+)\.(\d+)/) {
    if ("$4" eq '0') {
      return "$1.$2.$3";
    } else {
      return "$1.$2.$3cvs$4";
    }
  }
  return $_;
}

sub is_greater_version {
  my ($va, $vb) = @_;
  my @vaa = split(/\./, $va);
  my @vba = split(/\./, $vb);
  my $i = 0;
  while (defined($vaa[$i]) and defined($vba[$i])) {
    last if ($vaa[$i] != $vba[$i]);
    ++$i;
  }
  if (defined($vaa[$i]) and defined($vba[$i])) {
    return ($vaa[$i] > $vba[$i])? 1: 0;
  }
  return 0; # all equal, thus not greater
}

sub check_make_error {
  my ($log, $version, $recipients) = @_;
  open(LOG, "<$log") or die "opening $log: $!\n";
  my $last = <LOG>;
  while (<LOG>) { $last = $_ }
  close(LOG) or die "closing $log: $!\n" ;
  $_ = $last;
  if (/^make.*Error/) {
    my $message = qx,tail -120 $log,;
    $message = "Last lines of $log follow:\n---\n" . $message;
    &mail_notify_for ($version, 'build failed', $message, $recipients);
    die "Finished with error. Check $log for details.\n"
  }
}

sub get_arch_list {
  my $arcf = shift;
  open(ARC, "<$arcf") or die "opening $arcf: $!\n";
  my @archs = ();
  while (<ARC>) {
    chomp;
    push(@archs, $_);
  };
  close(ARC) or die "closing $arcf: $!\n" ;
  return \@archs;
}

sub load_mail_recipients {
  my $mailsfile  = shift;
  if (defined($mailsfile) and -f $mailsfile) {
    my @recipients = ();
    open(MLF, "< $mailsfile") or die "Opening $mailsfile: $!\n";
    while (<MLF>) {
      chomp;
      die "Invalid mail address in $mailsfile: $_\n" unless (/^.*@.*$/);
      push (@recipients, $_);
    }
    close(MLF) or die "Closing $mailsfile: $!\n";
    return \@recipients unless ($#recipients < 0);
  }
  return undef;
}

sub mail_notify_for {
  my ($version, $summary, $message, $recipients) = @_;
  if (defined($recipients)) {
    my %mail = (
      'From' => 'noreply@hydra.debian.net',
      'Subject' => "[HYDRA] Build $version : $summary",
      'Message' => $message . "\n\nYour friendly hydra script.\n",
    );
    foreach my $recipient (@$recipients) {
      $mail{'To'} = $recipient; 
      sendmail(%mail) or die $Mail::Sendmail::error;
    }
  }
}

chdir($RUN);

&refresh_module ("claws");

$VER = &get_version ("claws/configure.ac");
$OLD = &get_version ("claws-dev/configure.ac");
$RVER = &get_real_version ($VER);
$ROLD = &get_real_version ($OLD);
$WHO = &load_mail_recipients ("etc/mailing.list");

if (&is_greater_version ($VER, $OLD)) {
  mkdir("logs") unless (-d "logs");
  my $logname = "logs/hydra.$VER.log";

  if ($OLD ne '0.0.0.0') {
    print "Cleaning previous version $OLD\n";
    qx,make -f $MKD VERS=$ROLD clean >> $logname 2>&1,;
  }
  print "Cleaning status\n";
  qx,make -f $MKS clean >> $logname 2>&1,;
  print "Building new version $VER\n";
  qx,make -f $MKD VERS=$RVER >> $logname 2>&1,;
  &check_make_error($logname, $RVER, $WHO);
  print "Updating status for version $VER\n";
  qx,make -f $MKS VERS=$RVER status-source >> $logname 2>&1,;

  my $architectures = &get_arch_list("etc/architectures");
  foreach my $ARCH (@$architectures) {
    if ($OLD ne '0.0.0.0') {
      print "Archiving previous $OLD packages for $ARCH\n";
      qx,make -f $MKA VERS=$ROLD ARCH=$ARCH backup >> $logname 2>&1,;
      print "Cleaning previous $OLD build for $ARCH\n";
      qx,make -f $MKA ARCH=$ARCH clean >> $logname 2>&1,;
    }
    print "Building new claws $VER packages for $ARCH\n";
    qx,make -f $MKA VERS=$RVER ARCH=$ARCH claws-deb-$ARCH >> $logname 2>&1,;
    &check_make_error($logname, $RVER, $WHO);
    print "Updating repository for $ARCH\n";
    qx,make -f $MKA VERS=$RVER ARCH=$ARCH update-extra-$ARCH >> $logname 2>&1,;
    print "Updating status for $ARCH\n";
    qx,make -f $MKS VERS=$RVER ARCH=$ARCH status-$ARCH >> $logname 2>&1,;
  }
  if (-f "etc/verbose") {
    print "Build $RVER finished\n";
    mail_notify_for($RVER, 'build completed', 'Build was probably successful.', $WHO);
  }
}
else {
  if (-f "etc/verbose") {
    my $msg = "Not building $RVER as $ROLD is already built\n";
    print $msg;
    mail_notify_for($RVER, 'build skipped', $msg, $WHO);
  }
  exit 1;
}

exit 0;

