#!/usr/bin/perl -w
#
# hydra² - Claws Mail CVS Debian Packages Autobuilder script (again!)
#
# Copyright (c) 2008-2011 Ricardo Mones <ricardo@mones.org>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy  of this  software and  associated  documentation  files  (the
# "Software"), to deal in the  Software without  restriction, including
# without  limitation  the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or  sell copies  of the  Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The  above  copyright  notice and  this  permission  notice  shall be
# included in  all  copies  or substantial  portions  of the  Software.
#
# THE  SOFTWARE IS  PROVIDED "AS IS",  WITHOUT  WARRANTY OF  ANY  KIND,
# EXPRESS  OR  IMPLIED,  INCLUDING BUT  NOT LIMITED  TO THE  WARRANTIES
# OF  MERCHANTABILITY,   FITNESS   FOR   A   PARTICULAR   PURPOSE   AND
# NONINFRINGEMENT. IN  NO EVENT SHALL THE AUTHORS OR  COPYRIGHT HOLDERS
# BE  LIABLE FOR ANY CLAIM,  DAMAGES OR OTHER  LIABILITY, WHETHER IN AN
# ACTION  OF  CONTRACT, TORT OR  OTHERWISE, ARISING  FROM, OUT OF OR IN
# CONNECTION  WITH THE  SOFTWARE OR  THE USE OR  OTHER  DEALINGS IN THE
# SOFTWARE.
#
use strict;
use encoding 'utf8';

my $CVS = ':pserver:anonymous@claws-mail.org:/';
my $MKD = 'Makefile.dist';
my $MKA = 'Makefile.arch';
my $MKS = 'Makefile.stat';
my $VER = undef;
my $OLD = undef;

sub refresh_module {
  my $mod = shift; # claws or plugins
  if (-d $mod) {
    chdir($mod);
    qx,cvs -z3 update > /dev/null 2>&1,;
    chdir("..");
  } else {
    qx,cvs -z3 -d$CVS checkout -r gtk2 $mod > /dev/null 2>&1,;
  }
}

sub get_version {
  my $acfile = shift;
  my @ver = ("0", "0", "0", "0");
  if (-f $acfile) {
    open(AC, "< $acfile") or die "opening $acfile: $!\n";
    my $i = 0;
    while (<AC>) {
      chomp;
      if (/MAJOR_VERSION=(\d+)/) { $ver[0] = $1; ++$i; }
      if (/MINOR_VERSION=(\d+)/) { $ver[1] = $1; ++$i; }
      if (/MICRO_VERSION=(\d+)/) { $ver[2] = $1; ++$i; }
      if (/EXTRA_VERSION=(\d+)/) { $ver[3] = $1; ++$i; }
      last unless ($i lt 4);
    }
    close(AC) or die "closing configure.ac: $!\n";
  }
  return join('.', @ver);
}

sub get_real_version {
  $_ = shift;
  if (/(\d+)\.(\d+)\.(\d+)\.(\d+)/) {
    return "$1.$2.$3cvs$4";
  }
  return $_;
}

sub is_greater_version {
  my ($va, $vb) = @_;
  my @vaa = split(/\./, $va);
  my @vba = split(/\./, $vb);
  my $i = 0;
  while (defined($vaa[$i]) and defined($vba[$i])) {
    last if ($vaa[$i] != $vba[$i]);
    ++$i;
  }
  if (defined($vaa[$i]) and defined($vba[$i])) {
    return ($vaa[$i] > $vba[$i])? 1: 0;
  }
  return 0; # all equal, thus not greater
}

sub check_make_error {
  my $log = shift;
  open(LOG, "<$log") or die "opening $log: $!\n";
  my $last = <LOG>;
  while (<LOG>) { $last = $_ }
  close(LOG) or die "closing $log: $!\n" ;
  $_ = $last;
  die "Finished with error. Check $log for details.\n"
    if (/^make.*Error/);
}

sub get_arch_list {
  my $arcf = shift;
  open(ARC, "<$arcf") or die "opening $arcf: $!\n";
  my @archs = ();
  while (<ARC>) {
    chomp;
    push(@archs, $_);
  };
  close(ARC) or die "closing $arcf: $!\n" ;
  return \@archs;
}
  
&refresh_module ("claws");
&refresh_module ("plugins");

$VER = &get_version ("claws/configure.ac");
$OLD = &get_version ("claws-dev/configure.ac");
my $RVER = &get_real_version($VER);
my $ROLD = &get_real_version($OLD);

if (&is_greater_version ($VER, $OLD)) {
  mkdir("logs") unless (-d "logs");
  my $logname = "logs/hydra.$VER.log";

  if ($OLD ne '0.0.0.0') {
    print "Cleaning previous version $OLD\n";
    qx,make -f $MKD VERS=$ROLD clean >> $logname 2>&1,;
    # &check_make_error($logname);
  }
  print "Building new version $VER\n";
  qx,make -f $MKD VERS=$RVER >> $logname 2>&1,;
  &check_make_error($logname);
  print "Updating status for version $VER\n";
  qx,make -f $MKS VERS=$RVER all-source >> $logname 2>&1,;

  my $architectures = &get_arch_list("etc/architectures");
  foreach my $ARCH (@$architectures) {
    if ($OLD ne '0.0.0.0') {
      print "Archiving previous $OLD packages for $ARCH\n";
      qx,make -f $MKA VERS=$ROLD ARCH=$ARCH backup >> $logname 2>&1,;
      # &check_make_error($logname);
      print "Cleaning previous $OLD build for $ARCH\n";
      qx,make -f $MKA ARCH=$ARCH clean >> $logname 2>&1,;
      # &check_make_error($logname);
    }
    print "Building new claws $VER packages for $ARCH\n";
    qx,make -f $MKA VERS=$RVER ARCH=$ARCH claws-deb-$ARCH >> $logname 2>&1,;
    &check_make_error($logname);
    print "Building new plugins $VER packages for $ARCH\n";
    qx,make -f $MKA VERS=$RVER ARCH=$ARCH plugins-deb-$ARCH >> $logname 2>&1,;
    &check_make_error($logname);
    print "Updating repository for $ARCH\n";
    qx,make -f $MKA VERS=$RVER ARCH=$ARCH update-extra-$ARCH >> $logname 2>&1,;
    print "Updating status for $ARCH\n";
    qx,make -f $MKS VERS=$RVER ARCH=$ARCH all-$ARCH >> $logname 2>&1,;
  }
}

