
status-source: version status-source-last-change
	echo "IDLE" > $@

status-$(ARCH): version-$(ARCH) status-$(ARCH)-last-change
	echo "IDLE" > $@

status-source-last-change:
	date -r ./claws-mail-$(VERS).tar.gz > $@

version:
	echo $(VERS) > $@

status-$(ARCH)-last-change:
	date -r claws-deb-$(ARCH)/claws-mail_$(VERS)-*_$(ARCH).changes > $@

version-$(ARCH):
	echo $(VERS) > $@

clean:
	rm -f status-*
	rm -f version version-*

mrproper: clean

.PHONY: clean mrproper

